### ISSUE TITLE
PR lined up

### ISSUE THREAD

**Issue by ustulation** [debris/tiny-keccak#10]
There's a [useful PR here](https://github.com/debris/tiny-keccak/pull/7). It hasn't been commented on or merged. Could it be merged (or commented on if there's anything holding it back) ?

**Comment by debris** [comment]
I completely forgot about it. Thanks for reminding. I didn't want to merge rustfmt changes. The new release - 1.2.0 has wrapper methods for all common keccak functions

**Comment by ustulation** [comment]
Ah right - thanks !
