### ISSUE TITLE
1.4.1 is adding 20kb to wasm binaries size

### ISSUE THREAD

**Issue by NikVolf** [debris/tiny-keccak#28]
compared to 1.4.0

**Comment by newpavlov** [comment]
Take a look at [`sha3`](https://github.com/RustCrypto/hashes) crate, it [does not unroll](https://github.com/RustCrypto/sponges/blob/master/keccak/src/lib.rs#L140) outermost loop, which significantly reduces binary size and even improves performance a bit.

**Comment by Vurich** [comment]
Thanks for tagging me in this. I meant to do this a while ago (the author of `sha3` put in a PR to link to their code so I had a look at it and noticed that they'd rerolled the outer loop) but then just, um, didn't. On it now.

**Comment by Vurich** [comment]
One thing that makes explicit loop unrolling a bit of a deal with the devil is that LLVM doesn't seem to autovectorise unrolled loop code, only "real" loops. LLVM's autovectorisation isn't perfect but until we get simd on stable it's the best we have.

**Comment by debris** [comment]
fixed in #30
