### ISSUE TITLE
Is it, uh, safe to use this for anything?

### ISSUE THREAD

**Issue by quadrupleslap** [debris/tiny-keccak#6]
`rust-crypto` has a disclaimer in the README warning that it isn't ready for production, and hasn't been audited. I'm *guessing* there's a similar caveat for this crate, but I just thought I'd confirm it before giving up and hooking into C libraries.

**Comment by debris** [comment]
It hasn't been audited by anyone apart my colleagues. it **should** be safe, although I disclaim any liability.

It [is used in production](https://github.com/ethcore/parity/blame/master/ethcrypto/Cargo.toml#L8) already for several moths by parity-ethereum client which powers about 50% of miners of ethereum network, which is worth ~800mln usd
