### ISSUE TITLE
Bounds checking

### ISSUE THREAD

**Issue by burdges** [debris/tiny-keccak#9]
I believe there is a trick to avoid the bounds checking without unsafe code by consolodating the bound checks to the beginning and end of the loop.  I forget exactly how it works though, maybe using a slice `[..]` or something.

**Comment by debris** [comment]
I believe that latest version of `tiny-keccak` does not perform bounds checking, cause it in benchmarks on my machine (macos) it's as fast as original C implementation.

**Comment by rphmeier** [comment]
Out of curiosity, I'm gonna experiment a bit with typenum and exporting type aliases for common variants and see how that affects the bounds checking.

**Comment by rphmeier** [comment]
@burdges I found a trick which may be the one you were referencing:

instead of `fn xorin(&mut [u8], &[u8], usize)` with unsafe indexing,
just

```rust
fn xorin(dst: &mut [u8], src: &[u8]) {
    for (d, i) in dst.iter_mut().chain(src) {
        *d ^= *i
    }
}
```

and restrict the lengths of the slices at the call site.

**Comment by burdges** [comment]
That works?  I found it in Rust commit 6a7bc47.  I write stuff like this sometimes : 
```
    let mut i = s.len();
    let s = &mut s[..i];  // elide bounds checks; see Rust commit 6a7bc47
```
I've used this to removed the `unsafe` from `xorin` in https://github.com/debris/tiny-keccak/pull/8/commits/5bced87cffc3b4b203eb439b00adcadf9cbe48d2

**Comment by burdges** [comment]
Oh I missed that you submitted https://github.com/debris/tiny-keccak/pull/11 which does this differently.

**Comment by rphmeier** [comment]
Seems like both tricks get me the same performance in benches, although I haven't looked at generated assembly yet.

**Comment by burdges** [comment]
You eliminated more `unsafe`s than I did though.  I'm not sure your iterator comment works though.  If so, maybe only because you're using a fixed length array.
